name: CD workflow for backend application

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "starter/backend/**"

jobs:
  Lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: pip install pipenv
        run: pip install pipenv

      - name: pipenv install dependencies
        run: pipenv install

      - name: run lint
        run: pipenv run lint
  
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Use Python 3
      uses:  actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: pip install pipenv
      run: pip install pipenv

    - name: pipenv install dependencies
      run: pipenv install

    - name: Test
      run: pipenv run test

  Build:
    needs: [Test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend

    steps:
    - name: Check the Repository
      uses: actions/checkout@v3
      
    - name: Use Python 3
      uses:  actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: pip install pipenv
      run: pip install pipenv

    - name: pipenv install dependencies
      run: pipenv install


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to ecr
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      env:
        IMAGE_TAG: latest
        REPO_NAME: backend
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag 204215116418.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:$IMAGE_TAG .
        docker push 204215116418.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:$IMAGE_TAG

    - name: Run init.sh
        run: cd ./setup && ./init.sh || true

    - name: Update k8s
      run:
       aws eks update-kubeconfig --name cluster --region us-east-1

    - name: Deploy Docker Image to Amazon EKS
      run: |
        kustomize edit set image backend=204215116418.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        kustomize build | kubectl apply -f 
