name: CI workflow for backend application

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "starter/backend/**"

jobs:
  Lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: pip install pipenv
        run: pip install pipenv

      - name: pipenv install dependencies
        run: pipenv install

      - name: run lint
        run: pipenv run lint
  
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Use Python 3
      uses:  actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: pip install pipenv
      run: pip install pipenv

    - name: pipenv install dependencies
      run: pipenv install

    - name: Test
      run: pipenv run test

  Build:
    needs: [Test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v3
      
    - name: Use Python 3
      uses:  actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: pip install pipenv
      run: pip install pipenv

    - name: pipenv install dependencies
      run: pipenv install

    - name: Build and Push Docker Image
      env:
        IMAGE_TAG: latest
        REPO_NAME: backend
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag 204215116418.dkr.ecr.us-east-1.amazonaws.com/backend:latest .
